# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cfccfc38c9f04e2f953c3e738d23834e2b42155491e32fba9389db42a6b1235661b26766bcd00cf31c631fdfaede294f13b796b729494d5eef9ffe5d153ab55

test:
  secret_key_base: e59e4805da6fca95ac407661a0facd9c576c5a9eec0db49cfe1893a22bc2fd9bf97a67f1d2906abce6f79952e5b4dd8ce31463f85e00fb70956a1b05dda36653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
